### ISSUE TITLE
Exposure intervals beginning past study end

### ISSUE THREAD

**Issue by MatthewCaseres** [mattheaphy/actxps#24]
https://www.actuarialopensource.org/actxps_experienceanalysis_2023_02_03.html#right-trunc

**Comment by mattheaphy** [comment]
Thanks. This looks like a leap year issue too. Specifically, a 1-day stub period can be created when (1) a policy was issued on 3/1 of a non-leap year and (2) the study end date is a leap day. During the exposure process, the total exposure period is determined for each policy. This informs the number of exposure records that will be created for each policy. 

The calculation for the total exposure period (assuming exposure years) works like this:
`total exposure length = # fractional years from the issue date - 1 to the study end date`

Let's say the issue date is 2019-03-01 and the study end date is 2020-02-29. That gets turned into an interval from 2019-02-28 to 2020-02-29, which is a year and a day, or 1.003 years. That in turn becomes two periods (again 1 year and 1 day), and the second period starts on 2020-03-01.

The fix is simple. I'll put a filter so that the extraneous row is dropped.
