### ISSUE TITLE
Scaling factor or significant number input for weights in autotable

### ISSUE THREAD

**Issue by YasminAnuar** [mattheaphy/actxps#40]
Is it possible to add a scaling factor or significant number input for displaying the weighted variable in the autotable function? For example, if I'm trying to show number of claims weighted by face in millions in the summarised autotable, it would be helpful to be able to do it through the autotable function instead of changing the underlying data/having additional lines of code. 

Additionally, if the scaling could be added to the bottom of the resulting table, similar to how it currently shows "Study Range" and "Results weighted by" for presentation clarity. I like how the table looks otherwise though :D

**Comment by mattheaphy** [comment]
I have a draft solution for this here: https://github.com/mattheaphy/actxps/blob/split/R/tables.R

Rather than targeting the weighting variables directly, I thought it made sense to format all "amount columns" which I defined as follows:

- Termination studies - # claims, claim amounts, exposures
- Transaction studies - # transactions, total transactions, average transactions

New inputs:

- `decimals_amt` - number of decimals to display for amount columns
- `suffix_amt` - if `TRUE`, all amount columns will automatically be scaled. Scaling is handled by the gt function [fmt_number()](https://gt.rstudio.com/reference/fmt_number.html). Values can be converted into thousands, millions, billions, or trillions. An appropriate suffix is added to each number, so a footnote wouldn't even be necessary. For example, 123,456,789 becomes 123M, 123,456 becomes 123K, and 123 would remain unchanged.
